name: Dev workflow
on: 
  push:
    branches: 
      - "dev/**"
env:
  docker_username: ${{ github.actor }}
  docker_password: ${{ secrets.GITHUB_TOKEN }}
  GIT_COMMIT: ${{ github.sha }}
jobs:
  Build:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Build application
        run: ci/build-app.sh
      - name: Test application
        run: ci/unit-test-app.sh
      - name: Upload built artifact
        uses: actions/upload-artifact@v4
        with:
          name: built-app
          path: .
  Linting:
    runs-on: ubuntu-latest
    needs: [Build]
    steps:
      - name: Download an artifact
        uses: actions/download-artifact@v4
        with:
          name: built-app
          path: .
      - name: run linting
        uses: super-linter/super-linter/slim@v5 
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DISABLE_ERRORS: true  
  Docker-image:
    runs-on: ubuntu-latest
    needs: [Build]
    permissions:
      packages: write 
    steps:
      - name: Download an artifact
        uses: actions/download-artifact@v4
        with:
          name: built-app
          path: .
      - name: build docker
        run: bash ci/build-docker.sh
