name: Main workflow
on: push
jobs:
  Build:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Build application
        run: ci/build-app.sh

      - name: Test application
        run: ci/unit-test-app.sh
     
